# Generated by Django 5.0.6 on 2024-05-10 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Koperasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('pembayaran', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_barang', models.CharField(max_length=100)),
                ('nama_barang', models.TextField()),
                ('kasir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk', to='Koperasi.kasir')),
            ],
        ),
    ]
