# Generated by Django 5.0.6 on 2024-05-10 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Koperasi', '0002_pembeli_produk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kasir',
            old_name='nama_barang',
            new_name='id_barang',
        ),
        migrations.RenameField(
            model_name='kasir',
            old_name='harga',
            new_name='total_pembayaran',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='kasir',
        ),
        migrations.AddField(
            model_name='kasir',
            name='Produk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kasir', to='Koperasi.produk'),
            preserve_default=False,
        ),
    ]
